### ISSUE TITLE
Cannot import url_quote on local install

### ISSUE THREAD

**Issue by PeteBleackley** [prologic/sahriswiki#7] opened 2016-07-08 13:44 UTC
I don't have sudo on the server I'm planning to run sahriswiki on, so I've installed it with pip sahriswiki --user

When I try to run it with sahriswiki -- config <my_config> &, I get the following error message.

 from circuits.web.utils import url_quote, url_unquote
ImportError: cannot import name url_quote

**Comment by prologic** [comment] 2016-07-08 16:04
Let me see... What version of circuits got installed?

``` #!bash
$ python
Python 2.7.11 (default, Dec 26 2015, 17:47:53)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import circuits
>>> circuits.__version__
'3.2'
```

**Comment by PeteBleackley** [comment] 2016-07-08 16:08
3.2

**Comment by prologic** [comment] 2016-07-08 16:13
Cool. Looks like these two got removed at some point for some reason.

I'll hunt down the commit in circuits that did that for "why" and fix and
roll out a new version of sahriswiki.

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment] 2016-07-09 04:11
This was fixed in fefca7842975408368dc1cdc9e4004c6bdc12302

**Comment by prologic** [comment] 2016-07-09 04:12
Can you try installing from master?

**Comment by prologic** [comment] 2016-07-09 04:13
You can install from master with:

``` #!bash
pip install git+https://github.com/prologic/sahriswiki#egg=sahriswiki
```

**Comment by prologic** [comment] 2016-07-09 04:16
Confirmed to be working:

``` #!bash
(test)
$ sahriswiki
circuits.web/3.2 ready! Listening on: http://0.0.0.0:8000
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET / HTTP/1.1" 200 2949 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /css/screen.css HTTP/1.1" 200 4276 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /css/wiki.css HTTP/1.1" 200 2929 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /css/pygments.css HTTP/1.1" 200 3225 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /img/valid-xhtml10.png HTTP/1.1" 200 1076 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /img/valid-css.png HTTP/1.1" 200 1083 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /css/code.css HTTP/1.1" 200 117 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [08/Jul/2016:21:15:56] "GET /favicon.ico HTTP/1.1" 200 1422 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
```

**Closed as completed** 2017-01-08 18:36 UTC
